# Naming the workflow
name: Run weather.sh script

# Setting up the workflow so that it both runs daily at 10am and can be triggered mannually from the repository (Project task 2)
on:
  schedule:
    - cron: "0 10 * * *"

  workflow_dispatch:

# Giving the workflow permission to access and write to my repository
permissions:
  contents: write

jobs:
  # Using a Linux virtual machine for the workflow (Project task 3)
  run-weather-script:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Cloning the Repository (Project task 4)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Executing the weather.sh Script  (Project task 5)
      - name: Run weather.sh script
        run:  bash weather.sh

      # Step 3: Committing and pushing changes Back to my Repository (Project task 6)
      - name: Commit and push changes
        run: |
          git config --global user.name "NeilTynan"
          git config --global user.email "g00438902@atu.ie"
          git add .
          git commit -m '/workspaces/2425/data/weather'
          echo "Automated changes by weather.sh"
          git push origin main