name: Run weather.sh script

on:
  schedule:
    - cron: "40 15 * * *"

  workflow_dispatch:

jobs:
  run-weather-script:
    runs-on: unbuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather.sh script
        run: python weather.sh 

      - name: Commit and push changes
        run: 
          git config --global user.name "NeilTynan"
          git config --global user.email "g00438902@atu.ie"
          git add .
          git commit -m '/workspaces/2425/data/weather'
          echo "No changes to commit
          git push origin main"

 
